package sokoban;

/**
 * Where the application executes.<br>
 * It contains the public static void main that is meant to be the
 * only real entry point of the application.<br>
 * The other public static void main functions were generated by netbeans
 * and should not be considered to be valid.
 */
public class Sokoban {
    /**
     * Runs the application, accepting a "-console" argument to run the project in
     * Console Rendering mode.
     * @param args argument that can be set to "-console"
     */
    public static void main(String[] args) {
        Application app = new Application();
        
        if(args.length > 0 && args[0].equals("-console")){
            app.runConsole();
        }else{
            app.runSwing();
        }
    }
}
