/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sokoban.game.renderer.swing;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

import sokoban.game.Coord2DInt;
import sokoban.game.Game;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;

/**
 *
 * @author Tutas
 */
public class SwingGameFrame extends javax.swing.JFrame {

    /**
     * Creates new form SwingGameFrame
     */
    public SwingGameFrame(Game game) {
        setGame(game);
        initComponents();
    }

    Game g;

    protected Game _game;

    public void setGame(Game game){
        _game = game;
    }
    public Game getGame(){
        return _game;
    }
    public SwingGamePanel getGamePanel(){
        return (SwingGamePanel) jGamePanel;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jGamePanel = new SwingGamePanel(_game);
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jRestartItem = new javax.swing.JMenuItem();
        jSaveItem = new javax.swing.JMenuItem();
        jLoadItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jSaveLevel = new javax.swing.JMenuItem();
        jLoadLevel = new javax.swing.JMenuItem();
        jEditLevel = new javax.swing.JCheckBoxMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jAboutItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jGamePanelLayout = new javax.swing.GroupLayout(jGamePanel);
        jGamePanel.setLayout(jGamePanelLayout);
        jGamePanelLayout.setHorizontalGroup(
            jGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jGamePanelLayout.setVerticalGroup(
            jGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        jMenu3.setText("Game");

        jRestartItem.setText("Restart");
        jRestartItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRestartItemActionPerformed(evt);
            }
        });
        jMenu3.add(jRestartItem);

        jSaveItem.setText("Save");
        jSaveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveItemActionPerformed(evt);
            }
        });
        jMenu3.add(jSaveItem);

        jLoadItem.setText("Load");
        jLoadItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoadItemActionPerformed(evt);
            }
        });
        jMenu3.add(jLoadItem);

        jMenuBar2.add(jMenu3);

        jMenu1.setText("Level");

        jSaveLevel.setText("Save...");
        jSaveLevel.setActionCommand("SaveLevel");
        jSaveLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveLevelActionPerformed(evt);
            }
        });
        jMenu1.add(jSaveLevel);

        jLoadLevel.setText("Load...");
        jLoadLevel.setActionCommand("LoadLevel");
        jLoadLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoadLevelActionPerformed(evt);
            }
        });
        jMenu1.add(jLoadLevel);

        jEditLevel.setText("Edit");
        jEditLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditLevelActionPerformed(evt);
            }
        });
        jMenu1.add(jEditLevel);

        jMenuBar2.add(jMenu1);

        jMenu4.setText("Help");

        jAboutItem.setText("About");
        jAboutItem.setActionCommand("jAboutItem");
        jAboutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAboutItemActionPerformed(evt);
            }
        });
        jMenu4.add(jAboutItem);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jGamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jGamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAboutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAboutItemActionPerformed
        JOptionPane.showMessageDialog(this, "Made by Rui Simões #21605 @IPT 2023/2024");
    }//GEN-LAST:event_jAboutItemActionPerformed

    private void jLoadItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoadItemActionPerformed
        // TODO add your handling code here:
        load();
    }//GEN-LAST:event_jLoadItemActionPerformed

    private void load() {
        try{
            _game.input("load");
            jGamePanel.repaint();
        }catch(Exception e){

        }
    }

    private void jSaveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveItemActionPerformed
        // TODO add your handling code here:
        save();
    }//GEN-LAST:event_jSaveItemActionPerformed

    private void save() {
        try{
            _game.input("save");
            jGamePanel.repaint();
        }catch(Exception e){

        }
    }

    private void save(String file) {
        try{
            _game.save_file = file;
            _game.input("save");
            jGamePanel.repaint();
        }catch(Exception e){

        }
    }

    private void saveLevel(String file) {
        try{
            _game.saveLevel(file);
            jGamePanel.repaint();
        }catch(Exception e){
            SwingRenderer.renderException(this, e);
        }
    }

    private void loadLevel(String file) {
        try{
            _game.loadExternalLevel(file);
            jGamePanel.repaint();
        }catch(Exception e){
            SwingRenderer.renderException(this, e);
        }
    }

    private void jRestartItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRestartItemActionPerformed
        // TODO add your handling code here:
        restart();
    }//GEN-LAST:event_jRestartItemActionPerformed

    SwingEditFrame editFrame = null;
    private void jEditLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditLevelActionPerformed
        if(editFrame == null){
            editFrame = new SwingEditFrame(this);
            editFrame.setAlwaysOnTop(true);
            jEditLevel.setSelected(true);
            editFrame.pack();
            editFrame.setVisible(true);
            editFrame.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    super.windowClosing(e);
                    closeEditBox();
                }
            });
        }else{
            editFrame.dispose();
            closeEditBox();
        }
        getGamePanel().setEditing(editFrame != null);
    }//GEN-LAST:event_jEditLevelActionPerformed

    private void jLoadLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoadLevelActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Sokoban Level Data", "sokl"));
        fileChooser.setSelectedFile(new File("level.sokl"));
        int response = fileChooser.showOpenDialog(this);
        if(response == JFileChooser.APPROVE_OPTION){
            loadLevel(fileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_jLoadLevelActionPerformed

    private void jSaveLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveLevelActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Sokoban Level Data", "sokl"));
        fileChooser.setSelectedFile(new File("level.sokl"));
        int response = fileChooser.showSaveDialog(this);
        if(response == JFileChooser.APPROVE_OPTION){
            saveLevel(fileChooser.getSelectedFile().getAbsolutePath());
        }

    }//GEN-LAST:event_jSaveLevelActionPerformed

    public void closeEditBox(){
        editFrame = null;
        _game.setCursorPos(null);
        getGamePanel().setEditing(false);
        jEditLevel.setSelected(false);
        getGamePanel().repaint();
    }

    private void restart() {
        _game.start();
        jGamePanel.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jAboutItem;
    private javax.swing.JCheckBoxMenuItem jEditLevel;
    private javax.swing.JPanel jGamePanel;
    private javax.swing.JMenuItem jLoadItem;
    private javax.swing.JMenuItem jLoadLevel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jRestartItem;
    private javax.swing.JMenuItem jSaveItem;
    private javax.swing.JMenuItem jSaveLevel;
    // End of variables declaration//GEN-END:variables
}
